# R6 Internal Lab_AIML 

# TensorFlow

TensorFlow is a free and open-source software library for dataflow and differentiable programming across a range of tasks. It is a symbolic math library, and is also used for machine learning applications such as neural networks.

<img src="tf.jpg">

### Load tensorflow

In [1]:
import tensorflow as tf

### Enable Eager Execution if you are using tensorflow 1.x

In [2]:
tf.enable_eager_execution()

### Collect Data

In [3]:
import pandas as pd


In [4]:
data = pd.read_csv('prices.csv')

### Check all columns in the dataset

### Datatype of Column

In [5]:
data.dtypes

date       object
symbol     object
open      float64
close     float64
low       float64
high      float64
volume    float64
dtype: object

### Columns Name

In [6]:
data.columns

Index(['date', 'symbol', 'open', 'close', 'low', 'high', 'volume'], dtype='object')

### Drop columns `date` and  `symbol`

In [7]:
data=data.drop(columns=['date','symbol'],axis=1)

In [8]:
data.head()

open       close         low        high     volume
0  123.430000  125.839996  122.309998  126.250000  2163600.0
1  125.239998  119.980003  119.940002  125.540001  2386400.0
2  116.379997  114.949997  114.930000  119.739998  2489500.0
3  115.480003  116.620003  113.500000  117.440002  2006300.0
4  117.010002  114.970001  114.089996  117.330002  1408600.0

### Consider only first 1000 rows in the dataset for building feature set and target set

In [9]:
data=data.head(1000)

### Convert Float64 to Float32

In [10]:
data = data.astype('float32')


In [11]:
data.dtypes

open      float32
close     float32
low       float32
high      float32
volume    float32
dtype: object

### Divide the data into train and test sets

In [12]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import Normalizer

X1 = data.drop(columns= "close" , axis = 1)
Y1 = data["close"]


In [13]:
train_x, test_x,train_y,test_y = train_test_split(X1, Y1, test_size=.3, random_state=7)

### Normalize Train and Test Data 

In [15]:
import numpy as np

In [16]:
transformer = Normalizer()
X1_train= transformer.fit_transform(train_x)
Y_train = np.array(train_y)

## Building the graph in tensorflow

2.Define Weights and Bias

In [18]:
#We are initializing weights and Bias with Zero
w = tf.zeros(shape=(4,1))
b = tf.zeros(shape=(1))

3.Prediction

In [19]:
def prediction(x, w, b):
    
    xw_matmul = tf.matmul(x, w)
    y = tf.add(xw_matmul, b)
    
    return y

4.Loss (Cost) Function [Mean square error]

In [20]:
def loss(y_actual, y_predicted):
    
    diff = y_actual - y_predicted
    sqr = tf.square(diff)
    avg = tf.reduce_mean(sqr)
    
    return avg

5.GradientDescent Optimizer to minimize Loss [GradientDescentOptimizer]

In [21]:
def train(x, y_actual, w, b, learning_rate=0.01):
    
    #Record mathematical operations on 'tape' to calculate loss
    with tf.GradientTape() as t:
        
        t.watch([w,b])
        
        current_prediction = prediction(x, w, b)
        current_loss = loss(y_actual, current_prediction)
    
    #Calculate Gradients for Loss with respect to Weights and Bias
    dw, db = t.gradient(current_loss,[w, b])
    
    #Update Weights and Bias
    w = w - learning_rate*dw
    b = b - learning_rate*db
    
    return w, b

## Execute the Graph for 100 epochs and observe the loss

In [23]:
for i in range(100):
    
    w, b = train(X1_train, Y_train, w, b)
    print('Current Loss on iteration', i, loss(Y_train, prediction(X1_train, w, b)).numpy())

Current Loss on iteration 0 7663.568
Current Loss on iteration 1 7351.0693
Current Loss on iteration 2 7063.065
Current Loss on iteration 3 6797.6504
Current Loss on iteration 4 6553.033
Current Loss on iteration 5 6327.599
Current Loss on iteration 6 6119.838
Current Loss on iteration 7 5928.3647
Current Loss on iteration 8 5751.9062
Current Loss on iteration 9 5589.279
Current Loss on iteration 10 5439.4014
Current Loss on iteration 11 5301.2764
Current Loss on iteration 12 5173.9775
Current Loss on iteration 13 5056.66
Current Loss on iteration 14 4948.547
Current Loss on iteration 15 4848.9023
Current Loss on iteration 16 4757.0684
Current Loss on iteration 17 4672.4365
Current Loss on iteration 18 4594.4424
Current Loss on iteration 19 4522.562
Current Loss on iteration 20 4456.313
Current Loss on iteration 21 4395.265
Current Loss on iteration 22 4338.999
Current Loss on iteration 23 4287.1455
Current Loss on iteration 24 4239.3525
Current Loss on iteration 25 4195.3125
Current L

### Get the shapes and values of W and b

In [24]:
#Check Weights and Bias
print('Weights:\n', w.numpy())
print('Bias:\n',b.numpy())

Weights:
 [[2.5370645e-03]
 [2.5125619e-03]
 [2.5582330e-03]
 [3.3697968e+01]]
Bias:
 [33.69797]


### Linear Classification using Keras

### Building the simple Neural Network in Keras with one neuron in the dense hidden layer.
#### Use Mean square error as loss function and sgd as optimizer

In [27]:
#Initialize Sequential Graph (model)
model = tf.keras.Sequential()

#Add Dense layer for prediction - Keras declares weights and bias automatically
model.add(tf.keras.layers.Dense(1, input_shape=(4,)))

#Compile the model - add Loss and Gradient Descent optimizer
model.compile(optimizer='sgd', loss='mse')

### Execute the model

In [28]:
model.fit(X1_train, Y_train, epochs=100)


Epoch 1/100
700/700 [==============================] - 2s 2ms/sample - loss: 5880.9117
Epoch 2/100
700/700 [==============================] - 0s 103us/sample - loss: 4027.5763
Epoch 3/100
700/700 [==============================] - 0s 103us/sample - loss: 3726.0782
Epoch 4/100
700/700 [==============================] - 0s 103us/sample - loss: 3687.5519
Epoch 5/100
700/700 [==============================] - 0s 123us/sample - loss: 3684.2323
Epoch 6/100
700/700 [==============================] - 0s 110us/sample - loss: 3681.3059
Epoch 7/100
700/700 [==============================] - 0s 122us/sample - loss: 3680.0145
Epoch 8/100
700/700 [==============================] - 0s 110us/sample - loss: 3679.6970
Epoch 9/100
700/700 [==============================] - 0s 122us/sample - loss: 3682.9280
Epoch 10/100
700/700 [==============================] - 0s 117us/sample - loss: 3679.4096
Epoch 11/100
700/700 [==============================] - 0s 116us/sample - loss: 3681.9019
Epoch 12/100
700/700 

700/700 [==============================] - 0s 49us/sample - loss: 3681.4029
Epoch 93/100
700/700 [==============================] - 0s 54us/sample - loss: 3681.1726
Epoch 94/100
700/700 [==============================] - 0s 53us/sample - loss: 3681.3328
Epoch 95/100
700/700 [==============================] - 0s 53us/sample - loss: 3680.8514
Epoch 96/100
700/700 [==============================] - 0s 51us/sample - loss: 3680.7738
Epoch 97/100
700/700 [==============================] - 0s 53us/sample - loss: 3685.4138
Epoch 98/100
700/700 [==============================] - 0s 47us/sample - loss: 3680.7018
Epoch 99/100
700/700 [==============================] - 0s 50us/sample - loss: 3682.2288
Epoch 100/100
700/700 [==============================] - 0s 56us/sample - loss: 3682.1130


In [29]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_2 (Dense)              (None, 1)                 5         
Total params: 5
Trainable params: 5
Non-trainable params: 0
_________________________________________________________________


In [30]:
model.get_weights()

[array([[ 1.2125843 ],
        [ 1.1660832 ],
        [ 0.12595342],
        [34.796646  ]], dtype=float32), array([33.90037], dtype=float32)]

# Keras

Keras is an open-source neural-network library written in Python. It is capable of running on top of TensorFlow, Microsoft Cognitive Toolkit, Theano, or PlaidML. Designed to enable fast experimentation with deep neural networks, it focuses on being user-friendly, modular, and extensible

<img src="kr.png">

### Classification using Keras 

### Load the given Iris data using pandas (Iris.csv)

In [59]:
data1=pd.read_csv('iris.csv')

In [60]:
data1.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [61]:
data1.dtypes

Id                 int64
SepalLengthCm    float64
SepalWidthCm     float64
PetalLengthCm    float64
PetalWidthCm     float64
Species           object
dtype: object

In [62]:
data1.columns

Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')

### Splitting the data into feature set and target set

In [63]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import Normalizer

X2 = data1.drop(columns= ["Species"] , axis = 1)
Y2 = data1["Species"]


### Target set has different categories. So, Label encode them. And convert into one-hot vectors using get_dummies in pandas.

In [64]:
from sklearn.preprocessing import LabelEncoder

In [65]:
Y_processed = pd.DataFrame(Y2).apply(LabelEncoder().fit_transform)

In [66]:
testY = tf.keras.utils.to_categorical(Y_processed, num_classes=3)

In [67]:
testY

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

### Divide the dataset into Training and test (70:30)

In [68]:
from sklearn.model_selection import train_test_split
transformer = Normalizer()
#features = transformer.fit_transform(features)

train_x, test_x,train_y,test_y = train_test_split(X2, testY, test_size=.3, random_state=7)


### Model
Build the model with following layers: <br>
1. First dense layer with 10 neurons with input shape 4 (according to the feature set) <br>
2. Second Dense layer with 8 neurons <br>
3. Output layer with 3 neurons with softmax activation (output layer, 3 neurons as we have 3 classes) <br>
4. Use SGD and categorical_crossentropy loss 

In [69]:
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.BatchNormalization())

model.add(tf.keras.layers.Dense(10, activation='relu', input_shape=(4,)))
model.add(tf.keras.layers.Dense(8, activation='relu'))
model.add(tf.keras.layers.Dense(3, activation='softmax'))

#Create optimizer with non-default learning rate
sgd_optimizer = tf.keras.optimizers.SGD(lr=0.03)

#Compile the model
model.compile(optimizer=sgd_optimizer, loss='categorical_crossentropy', metrics=['accuracy'])

### Fitting the model and predicting 

In [70]:
#train model
model.fit(train_x.values,train_y, validation_split=0.2, epochs=30)

Train on 84 samples, validate on 21 samples
Epoch 1/30
84/84 [==============================] - 2s 19ms/sample - loss: 1.3390 - acc: 0.3929 - val_loss: 2.8533 - val_acc: 0.4286
Epoch 2/30
84/84 [==============================] - 0s 262us/sample - loss: 1.2938 - acc: 0.4048 - val_loss: 1.8908 - val_acc: 0.4286
Epoch 3/30
84/84 [==============================] - 0s 250us/sample - loss: 1.2163 - acc: 0.4048 - val_loss: 1.5584 - val_acc: 0.4286
Epoch 4/30
84/84 [==============================] - 0s 250us/sample - loss: 1.1723 - acc: 0.4048 - val_loss: 1.3721 - val_acc: 0.4286
Epoch 5/30
84/84 [==============================] - 0s 238us/sample - loss: 1.1484 - acc: 0.4405 - val_loss: 1.2730 - val_acc: 0.4286
Epoch 6/30
84/84 [==============================] - 0s 286us/sample - loss: 1.1139 - acc: 0.3929 - val_loss: 1.2087 - val_acc: 0.4286
Epoch 7/30
84/84 [==============================] - 0s 310us/sample - loss: 1.0812 - acc: 0.4048 - val_loss: 1.1582 - val_acc: 0.4286
Epoch 8/30
84/84 [=

### Report Accuracy of the predicted values

In [71]:
ypredict=model.predict(test_x)
ypredict

array([[0.02100772, 0.16653736, 0.8124549 ],
       [0.06521289, 0.25488845, 0.67989874],
       [0.49591598, 0.28518704, 0.21889697],
       [0.07896276, 0.27666146, 0.64437574],
       [0.05349847, 0.22867744, 0.7178241 ],
       [0.30951464, 0.33809736, 0.35238805],
       [0.1070906 , 0.33774567, 0.55516374],
       [0.06130484, 0.2534972 , 0.6851979 ],
       [0.4778663 , 0.33158568, 0.19054806],
       [0.11349843, 0.33172393, 0.5547777 ],
       [0.05662468, 0.26184878, 0.6815266 ],
       [0.05920488, 0.25549978, 0.6852953 ],
       [0.5307248 , 0.26223326, 0.20704192],
       [0.02126831, 0.17869565, 0.800036  ],
       [0.388519  , 0.3651585 , 0.24632259],
       [0.06609537, 0.26211843, 0.67178625],
       [0.02640236, 0.19385523, 0.7797424 ],
       [0.01980502, 0.16805123, 0.8121437 ],
       [0.46549433, 0.28541306, 0.24909267],
       [0.33973867, 0.36909905, 0.29116228],
       [0.07590996, 0.27801615, 0.6460739 ],
       [0.0220114 , 0.17791888, 0.80006975],
       [0.

In [72]:
model.evaluate(test_x,test_y)

45/45 [==============================] - 1s 18ms/sample - loss: 0.7669 - acc: 0.5778


[0.7668996572494506, 0.5777778]

In [74]:
model.summary()

Model: "sequential_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
batch_normalization_2 (Batch multiple                  20        
_________________________________________________________________
dense_9 (Dense)              multiple                  60        
_________________________________________________________________
dense_10 (Dense)             multiple                  88        
_________________________________________________________________
dense_11 (Dense)             multiple                  27        
Total params: 195
Trainable params: 185
Non-trainable params: 10
_________________________________________________________________
